#!/bin/bash

# Stock Screener Project - Quick Reference

echo "📊 Stock Screener Project Guide"
echo "=================================="
echo ""
echo "🚀 QUICK START (5 minutes)"
echo "  npm install && cd web && npm install && cd .."
echo "  npm run server              # Terminal 1"
echo "  cd web && npm run dev       # Terminal 2"
echo "  Open: http://localhost:3000"
echo ""
echo "📖 DOCUMENTATION"
echo "  QUICKSTART.md          - Get running quickly"
echo "  PROJECT_COMPLETE.md    - Full project overview"
echo "  README.md              - Detailed documentation"
echo "  web/README.md          - Frontend documentation"
echo "  SHELLS_GUIDE.md        - CLI usage guide"
echo ""
echo "💻 RUNNING MODES"
echo "  Web + API:          npm run server + cd web && npm run dev"
echo "  API Only:           npm run server"
echo "  CLI Only:           ./screener.sh [profile]"
echo "  Tests:              ./screener.sh test"
echo "  Advanced:           ./screener.sh advanced"
echo ""
echo "🔌 API ENDPOINTS (when running npm run server)"
echo "  POST /api/screen                - Universal screening"
echo "  POST /api/screen/market-cap     - Market cap filter"
echo "  POST /api/screen/pe             - P/E ratio filter"
echo "  POST /api/screen/gap            - Gap filter"
echo "  POST /api/screen/gap/large      - Large gap filter"
echo "  GET  /api/quote/:symbol         - Get stock quote"
echo "  GET  /api/profiles              - List profiles"
echo ""
echo "🎯 QUICK SCREENS AVAILABLE"
echo "  tech_growth            - Tech sector, P/E < 40"
echo "  large_gap              - Daily gap > 20%"
echo "  huge_gap               - Daily gap > 50%"
echo "  dividend_aristocrats   - Dividend yield > 3%"
echo "  large_cap              - Market cap > $10B"
echo "  small_cap              - Market cap $300M-$2B"
echo "  value_stocks           - P/E ratio < 15"
echo ""
echo "🛠️  USEFUL COMMANDS"
echo "  npm run server         - Start backend API"
echo "  npm run build          - Build backend for production"
echo "  npm run test           - Run test suite"
echo "  ./screener.sh help     - Show CLI help"
echo "  ./screener.sh large_gap - Run CLI screen"
echo ""
echo "💾 CONFIGURATION"
echo "  .env                   - Add FMP_API_KEY here"
echo "  web/vite.config.ts     - Frontend config"
echo "  web/.env               - Frontend env vars"
echo ""
echo "📁 PROJECT STRUCTURE"
echo "  /src                   - CLI & backend source"
echo "  /web                   - React frontend"
echo "  /tests                 - Test suite"
echo "  server.ts              - Express API server"
echo "  screener.sh            - CLI tool"
echo ""
echo "🐛 TROUBLESHOOTING"
echo "  Connection refused?        - npm run server not running"
echo "  No results?                - Check FMP API key in .env"
echo "  Port in use?               - Change port in config files"
echo "  TypeScript errors?         - npm install to update deps"
echo ""
echo "See QUICKSTART.md for detailed troubleshooting."
echo ""
echo "✨ Ready to screen stocks! 📈"
